"""Patrol system prompts — pre-defined fixed text templates.

Each patrol type has its own System Prompt that guides the Agent through
a specific scanning routine.  Prompts are **not** generated by the LLM —
they are hand-written constants to ensure stable, predictable behaviour
across patrol runs.

The prompt text itself lives in the central registry
(``backend/service/prompts.py``); this module re-exports it under the
historical constant names so ``patrol.py`` and existing tests keep working
unchanged.
"""

from __future__ import annotations

from backend.service.prompts import get_prompt

DAILY_PATROL_PROMPT = get_prompt("patrol.daily")[1]
WEEKLY_PATROL_PROMPT = get_prompt("patrol.weekly")[1]
CI_FAILURE_PATROL_PROMPT = get_prompt("patrol.ci_failure")[1]
JIRA_RESOLVED_PATROL_PROMPT = get_prompt("patrol.jira_resolved")[1]
